README.md
It was pointing to the Nubisa project instead of jxcore project.
=> Fxied known issues link

lib/jx/_jx_utils.js
I propose few changes to `jxcore.utils.console` methods.
1. There was a bug which raised an exception when the last param was null for `log()`:
```js
jxcore.utils.console.log("string", null);
//_jx_utils.js:335
//	  if(!arguments[arguments.length-1].split){
//	                                   ^
//TypeError: Cannot read property 'split' of null
```
2. Unified implementation of `write()` and `log()`
3. Compatibility with core's `console.log()`. Our methods were calling `toString()` per each object, while `console.log()` is stringifying. This was visible e.g. for {} objects or [] arrays:
```js
// our previous implementation:
jxcore.utils.console.log:
string [object Object] arr 1,2,3 true
// core's and our new implementation:
console.log:
string { x: 'test' } arr [ 1, 2, 3 ] true
```
4. …
=> jxcore.utils.console improvements

lib/child_process.js, test/simple/test-child-process-spawn-typeerror.js
1. The `spawn(cmd, {})` was throwing an exception (the type of `options` argument was compared to Array).
2. Also `execfile()` arguments parsing is redesigned.
=> updates for `spawn()`, `execfile()` and relevant test case

build_scripts/iosjb_compile.sh, src/node.cc
Hello.
I've packaged jx for jailbroken ios devices.
If the "jx" binary would be run in the shell, through "jx", and not a path, it would crash.
This small patch fixes that. It's probably not the best way, but it works for now.
Greetings,
vifino
=> IOS: Fix crash if jx is run on a jailbroken device

src/node.cc
Hello again.
This commit fixes `process.cwd()` and allows actual files to be run via relative paths on the commandline.
Without this, `process.cwd()` would always return the directory containing the binary itself, so module.js would try to load for example `/usr/bin/test.js` instead of `test.js` in the current directory.
=> iOS: Fix process.cwd on jb devices running binaries.

lib/jx/_jx_tasks.js, src/node.js
These commits provide the possibility to directly send params to tasks in an already JSON stringify'd format, through new methods exposed by JXcore that follow its previous syntax. 
jxcore.tasks.**_addTask**(method/object, **JSON Stringify'd param**, callback, obj)
jxcore.tasks.**_runOnce**(method, **JSON Stringify'd param**, doNotRemember)
jxcore.tasks.**_runOnThread**(threadId, method, **JSON Stringify'd param**, callback, obj)
method.**_runTask**(**JSON Stringify'd param**, callback, obj)
method.**_runOnce**(**JSON Stringify'd param**, doNotRemember)
This way tasks' params arrive already parsed into objects (because JX already uses JSON as its communication interface) without the need of another JSON.parse() call.
Follow the same rules of traditional tasks methods for all others …
=> New methods for sending JSON strings to tasks to be directly evaluated

src/jx/commons.h, src/wrappers/jxtimers_wrap.cc
Handle multiple items being expired from the memory store in the same loop. Using differing iteration methods for btree_map and std::map. When erasing things out of a btree_map all iterators are invalidated, except the one returned by the erase function itself. Therefore this value must be used. std::map c++98 erase doesn't return a value, so it cannot be used for std::map hence two methods are required.
Tested on heavy usage platform for several days without issue.
=> Handle multiple items being expired out of the memory store

lib/module.js
Fix for a reported issue io#1178. It also works for JXcore packaging.
issue:
require(".") should load ./index.js
=> allow require('.')

lib/jx/_jx_memStore.js
The old safeBlock requires the same closure for to be used every time. This is OK if you are only incrementing a counter, but say if you wanted to add a random value to a value in the memory store and always get the correct total, I cannot get it to work correctly.
One of the commit logs contains a function that demonstrates the bug.
This is pretty much a complete rewrite, and javascript isn't my forte, so shout if something doesn't look correct. It seems to work ok, although do you think it will break anything?
=> Safe Block function that can handle different closures

src/node.js
This update breaks the backward compatibility with runTask and runOnce calls straight from function.
=> remove tasking helpers from function prototype

lib/jx/_jx_monitorHelper.js
This was not always visible - mostly on slower platforms. The error occurred when `restart` was trying to launch the monitor while the previous was not completely closed yet.
=> monitor restart did not wait for monitor close

src/node.cc
similar to leveldown, moving sqlite version under process.versions.embedded
=> move sqlite version to process.versions.embedded

deps/uv/src/win/core.c
Certain compilers use C89 rules for compiling C sources. Declare variables at the start of blocks, instead of the middle of functions. Fixes Visual C++ 2010 Express build.
=> Fix compilation of core for compilers that use C89.

src/public/jx.cc, src/public/jx.h
Wrap uv_stop() and the macro in a public JX API, which can be
accessed from the android JNI interface.
=> API: add new embedding API for stopping the main loop

Makefile, lib/domain.js, src/node.js
- Fix remaining jslint errors in lib/domain.js & src/node.js
- Exclude lib/jx/_jx_marker.js from jslint
`make jslint` should _now_ pass with no errors
In general, I tried to match the code in Node v0.10 when fixing the jslint errors.
=> Fix remaining jslint errors

doc/api/util.markdown, lib/util.js
Used for conditional debugging. Depends on `NODE_DEBUG` env variable. [Ref issue](https://github.com/jxcore/jxcore/issues/571)
=> util.debuglog method added

doc/api/net.markdown, doc/api/path.markdown, doc/api/repl.markdown, doc/api/stream.markdown, lib/_stream_writable.js, lib/net.js, lib/path.js, lib/repl.js, test/simple/test-net-dns-lookup.js, test/simple/test-path.js, test/simple/test-repl-reset-event.js, test/simple/test-stream-writable-change-default-encoding.js, test/simple/test-stream-writev.js
[Adding methods from node v0.12.7 issue](https://github.com/jxcore/jxcore/issues/571)
Added `Writable.cork` method that forces buffering of all writes. [See docs](http://nodejs.org/dist/v0.12.7/docs/api/stream.html#stream_writable_cork).
Added `Writable.setDefaultEncoding` method. [See docs](http://nodejs.org/dist/v0.12.7/docs/api/stream.html#stream_writable_setdefaultencoding_encoding)
Added `path.isAbsolute` method. [See docs](https://nodejs.org/docs/latest-v0.12.x/api/path.html#path_path_isabsolute_path)
Added `lookup` event when calling `socket.connect` (triggers after `dns.lookup`). [See docs](https://nodejs.org/docs/latest-v0.12.x/api/net.html#net_event_lookup)
Added `reset` event to repl. Triggers when calling `.clear` from repl client. [See …
=> cork and uncork methods added in writable stream

Makefile, lib/_stream_writable.js, lib/jx/_jx_incoming.js, lib/jx/_jx_package.js, lib/net.js, lib/path.js, lib/repl.js, src/wrappers/node_crypto.cc, src/wrappers/tcp_wrap.cc, test/simple/test-domain.js, test/simple/test-process-config.js
Fixes so far (#585):
- Copied `test/simple/test-process-config.js` from Node 0.10.x/0.12.x (but kept the existing file header), now passes OK
- ~~Quick fix to `src/jx/jx_instance.cc` to get background jobs to work in default V8 build configuration and pass `test/simple/test-api-tasks.js`~~
UPDATE(s):
- fixed jslint errors
=> Some fixes for 0.3.1.0

doc/native/Embedding_API_Details.md, src/public/jx_result.cc, src/public/jx_result.h, test/native-interface/direct-buffer/test-posix.cpp
Hi!
I added JX_GetBuffer() method to directly access contents, and a test case for it (I iterated for both engines 50 times, as asked in TESTING.md).
This facilititates direct&fast access to Buffer’s contents, no copying involved.
Furthermore, as it stands, JX_GetString() does not work for buffers. In the best case, it copies (slow) and terminates on ‘\0’ (incorrect behaviour for a general purpose buffer).
Even the test case return-buffer converts buffer to string with +’’ then expects a string in the native side, which is strange because it means it does not really test buffer access, rather string access. 
Any case, please accept my pull request.
Best Wishes,
Zsolt
=> added JX_GetBuffer() to native interface for accessing Buffers directly

.travis.yml, lib/jx/_jx_incoming.js, test/simple/test-dgram-broadcast-multi-process.js, test/simple/test-regress-GH-4015.js
I was able to run the simple test suite on both engines in Travis CI with these changes.
Note that there is a trick since Travis CI only seems to check the last script command when reporting a failure.
=> Travis CI cover simple test suite on Mozilla & V8 engines (for discussion)

src/public/jx.cc, src/public/jx_result.cc, test/native-interface/return-buffer/test-posix.cpp
It is a perfectly valid scenario in both Javascript and C/C++ to have a
buffer of zero length, so we must handle this. (strlen(nullptr) would
crash)
Please accept this pull request.
(Ran native test cases with both sm/v8 50 times)
Note that malloc(0) as per the C specs is not guaranteed to return NULL, it either returns NULL or a pointer that must not be dereferenced but can be safely passed to free(). In the latter case, JX_SetBuffer(&value,malloc(0),0) would still crash, so it is a bit unfortunate that len=0 default value corresponds to strlen(), it would be better to have, let’s say -1, but that would break compatibility.
Thanks!
ps: @treasurebox here, changed username just recently.
=> handle zero-length Buffer(0)

doc/HOW_TO_COMPILE.md
+ Added some extra comments regarding usage in os x.
+ Fixed typo in the static library section where the --shared-library flag was used.
=> Updated doc about building as shared library

doc/api/jxcore-process.markdown, lib/console.js, lib/util.js, src/node.cc, src/node.js
Detect when jxcore is running in a Windows GUI, and if so, don't use invalid file handles when allocating the js console object. This prevents an exception with the engine startup, which was stopping the source given to JX_DefineMainFile from running.
=> Fix embedding in a Windows non-console app, issue #608.

src/node_version.h
prior art:
``` sh
$ node -v
v0.10.40
$ npm -v
1.4.14
```
Personally, I would be okay with dropping the `v` entirely, but at the very least, removing the space would be beneficial. Aside from not following convention, the version string seems to be used as the lockfile name for npm. Which means jx is writing a file with a space in the name; that's just not nice. :)
=> omit space in version string

lib/fs.js, lib/jx/_jx_package.js, lib/module.js, src/node.js
This is implementation for keeping files/assets in binary format (not as base64 strings anymore) inside jx/native packages.
* keeps backwards compatibility:
* reads previous packages. **I take it as very important.**
* can also create previous packages if we use `--legacy` option for `jx package`. This is probably not needed to maintain further, but I left this only because literally 4 lines of code are taking care of it and they are easily detachable.
* is much faster now - 60% of previous result duration with bulk operation: creating a package and running/extracting it.
* packages gets also smaller (33% when packing jxcore-cordova-release)
* works on Windows (together with exe signing)
* passes all our tests
**Recent update:**
* during package execution assets are kept in memory store …
=> jxp binary format. Applies to #508, #611

src/jxcore.cc
When the AutoScope object goes out of scope in the JXEngine::Destroy method it uses members of main_node_ that prior to this fix had already been destroyed by the node::removeCommons() call. This fix moves the node::removeCommons autoside the lifetime scope of the AutoScope object, such that it's guaranteed that all members of main_node_ are still dereferenceable.
=> jxcore: moved node::removeCommons() outside AutoScope scope

src/jx/commons.cc
for java-script subengines the loopId member was not initialized, this causes a crash when running headless
=> jxcore: initialize loopId member of (uv) loop

common.gypi, vcbuild.bat
Same as #840
- Add --static-library option for vcbuild.bat
- Fix LNK1241 error on building static debug library with MSVC
=> Add --static-library option for vcbuild.bat

src/node.cc
Fix #608 somehow introduced a broken fix for supporting embedded headless client (like e.g. Windows UI applications). The 'hasStdFds' should indicate whether stdout/stdin/stderr is available, in #608 however it was true when the handle type for stdout was unknown. Changing this will result in crash when running subengine in a console. Pull request #836 will solve that issue.
=> jxcore: assign correct value to 'hasStdFds'

lib/crypto.js, lib/tls.js, src/wrappers/node_crypto.cc, src/wrappers/node_crypto.h, test/simple/test-tls-psk-circuit.js, test/simple/test-tls-psk-client-callback.js, test/simple/test-tls-psk-client-identity-key.js, test/simple/test-tls-psk-client-identity-nokey.js, test/simple/test-tls-psk-client-noidentity-key.js, test/simple/test-tls-psk-client.js, test/simple/test-tls-psk-server.js
This adds support for Pre-shared-keys using OpenSSL 1.0.x implementation and the currently supported PSK in OpenSSL which are:
```
PSK-AES256-CBC-SHA:PSK-3DES-EDE-CBC-SHA:PSK-AES128-CBC-SHA:
```
**Update: This PR/commit has been updated and corrected all macro usage cross V8/Moz. **
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/jxcore/jxcore/813)
=> adding pre-shared-key (psk) support for tls

build_scripts/android-configure.sh, src/wrappers/node_crypto.cc
Hi,
these are two commits from thaliproject/jxcore:
- Update toolchain for building ndk version
- Using utf8 instead of ascii for psk identity
Thank you.
=> Update toolchain and utf8 for psk identity

build_scripts/android_compile.sh, build_scripts/ios_compile.sh
jx may not be available on target machine + no installer support. So remove compress_internals requirements
=> build for mobile without compress_internals

src/node.js
This fixes: [App fails to load on some devices to error "No such native module"](https://github.com/thaliproject/Thali_CordovaPlugin/issues/594).
=> Fix for Android release builds.

deps/npm/node_modules/node-gyp/addon.gypi, deps/npm/node_modules/node-gyp/src/win_delay_load_hook.cc
This fixes: [leveldown mobile failing to install on Windows](https://github.com/thaliproject/Thali_CordovaPlugin/issues/763).
The node-gyp version that comes with npm 3.3.12 is incompatible with Visual Studio 2015.
The fix is the same fix applied for npm 3.4.0:
https://github.com/nodejs/node-gyp/commit/f31482e2260e3beb90d959c62135e5e95c06ed4d
In order to have this fix available after merging it, npmjx311.tar.gz needs to be recreated using deps/packnpm.sh.
Be aware that on a clean machine packnpm.sh produces a npmjx311.tar.gz file that may be different from the current version available online, it will miss the 'debug' sub-module for:
npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index
that will causing an error when installing the leveldown-mobile module.
I've …
=> Fixed leveldown-mobile failing to install on Windows.
