jxcore/jxcore

jx.gyp

removes unnecessary condition check for spider monkey build

minor cleanup

---

lib/jx/_jx_config.js
lib/jx/_jx_monitorHelper.js
lib/jx/_jx_multiplier.js
lib/jx/_jx_source.js
samples/jx_packaging/dren.js
src/node.js
src/wrappers/jxutils_wrap.cc
test/jxcore/test-exec-error.js
test/jxcore/test-monitor-kill.js
test/jxcore/test-monitor-run.js
test/jxcore/test-node_path_start.js
test/node_modules/jxtools/assert.js
test/node_modules/jxtools/index.js

1. Negative exit codes converted to positives.
2. Except for few test cases I didn't find any code which would rely on negative cmdSync().exitCode
3. Fixed exitCode for monitor tool - it was returning != 0 even if there was no error.

removed negative cmdSync exit code

---

src/public/jx.cc

removing an unnecessary code piece

fix cleanup

---

src/wrappers/jxtimers_wrap.cc

When expiring items out of the memory store, the locks are taken in the wrong order.
The modifier functions in src/wrappers/memory_wrap.cc take the locks in the reverse
order to this function, hence causes a race condition which can end in two threads
holding and waiting for a lock that the other holds.
Modified this function so that the timers lock is taken first, collects a list
of keys to delete, releases the timer lock and takes the store lock. The
result being that a dead lock is impossible.
Tested on a machine running jx core under high load. Dead lock has now not occurred for
72 hours. Previously dead locks occurred every 6 hours.

Bug Fix - Issue 240 -Deadlock when expiring items out of the memory store

---

src/node.js

Test whether a module cache is really a module cache before return it

Fixed #269

---

lib/fs.js

Clean commit of [this](https://github.com/jxcore/jxcore/pull/312) pull request.

fs extension: async fs.readFile() and fs.exists()

---

doc/api/jxcore-tasks.markdown
lib/jx/_jx_tasks.js
src/node.js

Conform to node-style callbacks

---

releaseLogs.txt

Merge 3.0.1 changelog back to master

add 3.0.1 changelog

---

.travis.yml

travis: do not update g++

---

src/node.js

Fixes https://github.com/jxcore/jxcore-cordova/issues/58

Android: LogCat process.stdout, process.stderr support

---

lib/buffer.js
src/wrappers/node_buffer.cc
src/wrappers/node_buffer.h
test/simple/test-buffer-v4.js

Related https://github.com/jxcore/jxcore/issues/523

Implement Buffer compare, and indexOf

---

lib/child_process.js

Passes test/simple/test-crypto-domains.js & test/simple/test-process-env.js

Fix child process environmental variables

---

lib/child_process.js

as suggested by @ktrzeciaknubisa 
My changes in #528 fixed a couple of tests from node.js but partially breaks the fix for #287. Fixed in this PR.

Fix PR #528 due to #287

---

lib/jx/_jx_argv.js
lib/jx/_jx_config.js
lib/jx/_jx_http_helper.js
lib/jx/_jx_incoming.js
lib/jx/_jx_install.js
lib/jx/_jx_loadEmbedded.js
lib/jx/_jx_memStore.js
lib/jx/_jx_monitor.js
lib/jx/_jx_monitorHelper.js
lib/jx/_jx_multiplier.js
lib/jx/_jx_package.js
lib/jx/_jx_parsers.js
lib/jx/_jx_source.js
lib/jx/_jx_subs.js
lib/jx/_jx_tasks.js
lib/jx/_jx_timers.js
lib/jx/_jx_utils.js

The diff is pretty big. I used `tools/closure_linter/closure_linter/fixjsstyle.py` to fix a _lot_ of the errors, with a little rework to the changes, but also had to fix a number of issues by hand. I decided to break the changes into per-file commits, along with some multi-file commits.
There is still an issue on `lib/jx/_jx_marker.js` which I will deal with later.
If these changes are accepted, I am happy to work on the other Javascript files.

Fix jslint errors in lib/jx

---

lib/fs.js

This commit fixes packaged files serving by ghost running as package: https://github.com/jxcore/jxcore/issues/524

better piping of createReadStream for packages

---

lib/console.js

cherry pick from node 0.12.7 by @karaxuna

options support for console.dir

---

doc/native/Embedding_Basics.md

Change RT_JSON to RT_Object to make an example work

update embedding sample

---

lib/jx/_jx_package.js
src/node.js

Uses a new method for finding the data to load; Fixes an issue with
signing a Windows executable

Efficiently repair reading of signed files

---

build_scripts/ARCH/README.md
build_scripts/ARCH/arm/PKGBUILD
build_scripts/ARCH/arm/README.md
build_scripts/ARCH/arm/jxcore.install
build_scripts/ARCH/aur/PKGBUILD
build_scripts/ARCH/aur/jxcore.install

modified:   build_scripts/ARCH/arm/PKGBUILD
deleted:    build_scripts/ARCH/arm/README.md
new file:   build_scripts/ARCH/arm/jxcore.install
renamed:    build_scripts/ARCH/PKGBUILD -> build_scripts/ARCH/aur/PKGBUILD
new file:   build_scripts/ARCH/aur/jxcore.install

modified: build_scripts/ARCH

---

src/wrappers/node_crypto.cc

[bug](https://github.com/jxcore/jxcore/issues/700) fixed

#700 chakra build error fixed

---

README.md
doc/HOW_TO_COMPILE.md
doc/api/README.markdown
doc/api/jxcore-uwp.markdown

https://github.com/jxcore/jxcore/issues/673

uwp docs updated

---

src/external/module_wrap.cc

https://github.com/jxcore/jxcore/issues/735

Uwp not implemented error text when engine not chakra

---

deps/npm/lib/utils/lifecycle.js

https://github.com/jxcore/jxcore/issues/740

Running lifecycle scripts from package.json fixed for npm

---

src/public/jx.cc

https://github.com/jxcore/jxcore/issues/753

Returning null from native function call fixed

---

test/native-interface/return-null/test-posix.cpp

https://github.com/jxcore/jxcore/issues/753

Test case added for native function returning null

---

deps/chakrashim/src/jsrtisolateshim.cc

Chakra: Enable Async/Await

---

lib/util.js

Also add a polyfill for Object.setPrototypeOf for v8 3.14.
See #799

#799 Replace util.inherits with node 5.5.0 implementation. 

---

src/jx/Proxy/Mozilla_340/MozJS/MozValue.cc
src/wrappers/node_crypto.cc

Not very many cases outside of deps.

remove unnecessary not null checks before delete

---

jx.gyp

as suggested in related ticket

fix building shared library on linux

---

README.md

**Nubisa halting active development on JXcore platform** 
http://www.nubisa.com/nubisa-halting-active-development-on-jxcore-platform/

Nubisa halting active development on JXcore platform

---

lib/tls.js
test/simple/test-tls-psk-circuit.js
test/simple/test-tls-psk-client-callback.js
test/simple/test-tls-psk-client-identity-key.js
test/simple/test-tls-psk-client-identity-nokey.js
test/simple/test-tls-psk-client-noidentity-key.js

Hi @obastemur 
another commit coming from thaliproject/jxcore by @cicorias.
Thank you.

allowing no pfx/cert on psk

---

deps/npm/.npmrc
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/.npmignore
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/History.md
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/Makefile
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/Readme.md
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/bower.json
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/browser.js
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/component.json
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/debug.js
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/node.js
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/node_modules/ms/.npmignore
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/node_modules/ms/History.md
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/node_modules/ms/LICENSE
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/node_modules/ms/README.md
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/node_modules/ms/index.js
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/node_modules/ms/package.json
deps/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/debug/package.json

This PR is related to https://github.com/jxcore/jxcore/pull/906

Add missing node-gyp submodule.

---

README.md

Added a link to https://github.com/janeasystems/nodejs-mobile/issues
If no objection by next day, I will merge this.

Give a reference link to nodejs mobile
